-- Generated by the database client.
CREATE TABLE posts(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    caption varchar(250),
    photo varchar(50),
    created_at timestamp without time zone DEFAULT (now())::timestamp without time zone,
    PRIMARY KEY(id),
    CONSTRAINT posts_user_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);