-- Generated by the database client.
CREATE TABLE follows(
    user_id uuid,
    follower_id uuid,
    CONSTRAINT follows_user_id_fkey FOREIGN key(user_id) REFERENCES users(id),
    CONSTRAINT follows_follower_id_fkey FOREIGN key(follower_id) REFERENCES users(id)
);