-- Generated by the database client.
CREATE TABLE users(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    fullname varchar(35) DEFAULT 'new user'::character varying,
    avatar varchar(60),
    bio varchar(100),
    email varchar(30),
    password varchar(100),
    created_at timestamp without time zone DEFAULT (now())::timestamp without time zone,
    updated_at timestamp without time zone,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);