-- Generated by the database client.
CREATE TABLE comments(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    post_id uuid,
    user_id uuid,
    comment varchar(500) NOT NULL,
    created_at timestamp without time zone DEFAULT (now())::timestamp without time zone,
    PRIMARY KEY(id),
    CONSTRAINT comments_post_id_fkey FOREIGN key(post_id) REFERENCES posts(id),
    CONSTRAINT comments_user_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);