-- Generated by the database client.
CREATE TABLE likes(
    post_id uuid,
    user_id uuid,
    CONSTRAINT likes_post_id_fkey FOREIGN key(post_id) REFERENCES posts(id),
    CONSTRAINT likes_user_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);