-- Generated by the database client.
CREATE TABLE commments(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    comment varchar(500) NOT NULL,
    created_at timestamp without time zone DEFAULT (now())::timestamp without time zone,
    PRIMARY KEY(id),
    CONSTRAINT commments_user_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);