definitions:
  models.AuthRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.BadRequestResponse:
    properties:
      code:
        example: 400
        type: integer
      error:
        example: Example bad request error...
        type: string
      is_success:
        example: false
        type: boolean
    type: object
  models.InteracTionPost:
    properties:
      comment:
        type: string
      is_like:
        description: User_id string  `db:"user_id" json:"user_id" binding:"required"`
        type: boolean
      post_id:
        type: string
    required:
    - post_id
    type: object
  models.InternalErrorResponse:
    properties:
      code:
        example: 500
        type: integer
      error:
        example: Example Internal server error...
        type: string
      is_success:
        example: false
        type: boolean
    type: object
  models.LoginResponse:
    properties:
      code:
        example: 200
        type: integer
      is_success:
        example: true
        type: boolean
      message:
        example: Example message success...
        type: string
      page:
        example: 1
        type: integer
      token:
        example: 'example : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        type: string
    type: object
  models.NotFoundResponse:
    properties:
      code:
        example: 404
        type: integer
      error:
        example: example, Not Found
        type: string
      is_success:
        example: false
        type: boolean
    type: object
  models.PostDetail:
    properties:
      caption:
        type: string
      created_at:
        type: string
      fullname:
        type: string
      photo:
        type: string
      post_id:
        type: string
      user_id:
        type: string
    type: object
  models.ProfileResponse:
    properties:
      avatar:
        type: string
      bio:
        type: string
      created_at:
        type: string
      fullname:
        type: string
      user_id:
        type: string
    type: object
  models.Response:
    properties:
      code:
        example: 200
        type: integer
      is_success:
        example: true
        type: boolean
      message:
        example: Example message success...
        type: string
      page:
        example: 1
        type: integer
    type: object
  models.ResponseData:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      is_success:
        example: true
        type: boolean
      message:
        example: Example message success...
        type: string
      page:
        example: 1
        type: integer
    type: object
  models.UnauthorizedResponse:
    properties:
      code:
        example: 401
        type: integer
      error:
        example: example Unauthorized, please login again...
        type: string
      is_success:
        example: false
        type: boolean
    type: object
host: 127.0.0.1:3000
info:
  contact: {}
  description: communicare your social app
  title: communicare
  version: "1.0"
paths:
  /{any}:
    get:
      description: if route not found, send 404 statusNotfound as response
      produces:
      - application/json
      responses:
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.NotFoundResponse'
      summary: testing display for no route
      tags:
      - NoRoute
  /auth/login:
    post:
      consumes:
      - application/json
      description: Melakukan autentikasi pengguna dengan email dan password.
      parameters:
      - description: body Login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login berhasil
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Email atau password kosong, atau email/password salah
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "404":
          description: Email tidak ditemukan atau email/password salah
          schema:
            $ref: '#/definitions/models.NotFoundResponse'
        "500":
          description: Kesalahan internal server
          schema:
            $ref: '#/definitions/models.InternalErrorResponse'
      summary: Login pengguna
      tags:
      - Auth
  /auth/logout:
    delete:
      description: Mem-blacklist JWT Token yang aktif untuk mengakhiri sesi.
      produces:
      - application/json
      responses:
        "200":
          description: Logout berhasil
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Kesalahan server internal saat mem-blacklist token
          schema:
            $ref: '#/definitions/models.InternalErrorResponse'
      security:
      - JWTtoken: []
      summary: Logout pengguna
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Mendaftarkan pengguna baru dengan email dan password.
      parameters:
      - description: Data Pendaftaran Pengguna (Email dan Password)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Pendaftaran berhasil
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: 'Validasi input gagal (misalnya: email tidak valid, password
            terlalu pendek, atau email sudah terdaftar)'
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "500":
          description: Kesalahan server internal
          schema:
            $ref: '#/definitions/models.InternalErrorResponse'
      summary: Pendaftaran pengguna baru
      tags:
      - Auth
  /social/follow/{user_id}:
    post:
      description: Memulai mengikuti pengguna lain berdasarkan ID pengguna. Membutuhkan
        otentikasi.
      parameters:
      - description: ID pengguna yang ingin diikuti
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil mengikuti pengguna
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: Token tidak valid atau tidak ada
          schema:
            $ref: '#/definitions/models.UnauthorizedResponse'
        "500":
          description: Kesalahan server internal
          schema:
            $ref: '#/definitions/models.InternalErrorResponse'
      security:
      - JWTtoken: []
      summary: Mengikuti Pengguna
      tags:
      - Social
  /social/post:
    get:
      description: Mengambil daftar postingan terbaru dari pengguna yang sudah di-follow
        oleh pengguna yang sedang login.
      produces:
      - application/json
      responses:
        "200":
          description: Daftar postingan berhasil dimuat
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.PostDetail'
                  type: array
              type: object
        "401":
          description: Token tidak valid atau tidak ada
          schema:
            $ref: '#/definitions/models.UnauthorizedResponse'
        "500":
          description: Kesalahan server internal
          schema:
            $ref: '#/definitions/models.InternalErrorResponse'
      security:
      - JWTtoken: []
      summary: Ambil Postingan dari Pengguna yang Diikuti (Feed)
      tags:
      - Social
    post:
      consumes:
      - application/json
      description: Memberi like pada postingan, menghapus like, atau menambahkan komentar
        pada postingan.
      parameters:
      - description: Detail interaksi (Post ID, status like, dan/atau komentar)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.InteracTionPost'
      produces:
      - application/json
      responses:
        "200":
          description: Interaksi (like/komentar) berhasil diproses
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Input tidak valid (misalnya Post ID kosong)
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "401":
          description: Token tidak valid atau tidak ada
          schema:
            $ref: '#/definitions/models.UnauthorizedResponse'
        "500":
          description: Kesalahan server internal
          schema:
            $ref: '#/definitions/models.InternalErrorResponse'
      security:
      - JWTtoken: []
      summary: Like atau Komentar Postingan
      tags:
      - Social
  /users:
    post:
      consumes:
      - multipart/form-data
      description: Memperbarui detail profil pengguna termasuk nama lengkap, bio,
        dan avatar. Membutuhkan otentikasi.
      parameters:
      - description: Nama lengkap pengguna
        in: formData
        name: fullname
        type: string
      - description: Bio/deskripsi singkat pengguna
        in: formData
        name: bio
        type: string
      - description: File gambar untuk Avatar (Max 2MB)
        in: formData
        name: profile_picture
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Profil berhasil diperbarui
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  $ref: '#/definitions/models.ProfileResponse'
              type: object
        "400":
          description: Input tidak valid atau kegagalan upload file
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "401":
          description: Token tidak valid atau tidak ada
          schema:
            $ref: '#/definitions/models.UnauthorizedResponse'
        "500":
          description: Kesalahan server internal
          schema:
            $ref: '#/definitions/models.InternalErrorResponse'
      security:
      - JWTtoken: []
      summary: Perbarui Profil Pengguna
      tags:
      - User
  /users/post:
    post:
      consumes:
      - multipart/form-data
      description: Mengunggah foto dan caption untuk membuat postingan baru. Membutuhkan
        otentikasi (JWT).
      parameters:
      - description: Teks caption untuk postingan
        in: formData
        name: caption
        type: string
      - description: File gambar untuk Postingan (Wajib)
        in: formData
        name: photo
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Postingan berhasil dibuat
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Input tidak valid, file tidak ditemukan, atau kegagalan upload
            file
          schema:
            $ref: '#/definitions/models.BadRequestResponse'
        "401":
          description: Token tidak valid atau tidak ada
          schema:
            $ref: '#/definitions/models.UnauthorizedResponse'
        "500":
          description: Kesalahan server internal
          schema:
            $ref: '#/definitions/models.InternalErrorResponse'
      security:
      - JWTtoken: []
      summary: Membuat Postingan Baru
      tags:
      - User
securityDefinitions:
  JWTtoken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
